###order-consul 服务端口号
server:
  port: 8503
spring:
  application:
    name: yc-member-consul
  ####consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /health
